### ISSUE TITLE
cargo cannot install clap

### ISSUE THREAD

**Issue by brianmay** [git-series/git-series#29] opened 2016-10-19 00:41 UTC
Am I doing something wrong? This is a Debian/stretch box:

```
% cargo install --root ~/.local git-series

    Updating registry `https://github.com/rust-lang/crates.io-index`
   Compiling bitflags v0.7.0
   Compiling vec_map v0.6.0
   Compiling bitflags v0.1.1
   Compiling ansi_term v0.8.0
   Compiling quick-error v1.1.0
   Compiling gcc v0.3.37
   Compiling colorparse v1.1.0
   Compiling num-traits v0.1.36
   Compiling ansi_term v0.9.0
   Compiling unicode-normalization v0.1.2
   Compiling unicode-width v0.1.3
   Compiling pkg-config v0.3.8
   Compiling libz-sys v1.0.6
   Compiling openssl-sys v0.7.17
   Compiling unicode-segmentation v0.1.2
   Compiling num-integer v0.1.32
   Compiling winapi-build v0.1.1
   Compiling kernel32-sys v0.2.2
   Compiling strsim v0.5.1
   Compiling matches v0.1.3
   Compiling unicode-bidi v0.2.3
   Compiling idna v0.1.0
   Compiling url v1.2.1
   Compiling winapi v0.2.8
   Compiling libc v0.2.17
   Compiling rand v0.3.14
   Compiling time v0.1.35
   Compiling term_size v0.2.1
   Compiling clap v2.14.0
.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.14.0/src/errors.rs:857:35: 857:46 error: no method named `description` found for type `std::fmt::Error` in the current scope
.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.14.0/src/errors.rs:857         Error::with_description(e.description(), ErrorKind::Format)
                                                                                                                ^~~~~~~~~~~
error: aborting due to previous error
error: failed to compile `git-series v0.8.10`, intermediate artifacts can be found at `/tmp/brian/cargo-install.hSw3fAyyTNbG`

Caused by:
  Could not compile `clap`.

To learn more, run the command again with --verbose.
```

**Comment by joshtriplett** [comment] 2016-10-19 05:16
You're not doing anything wrong.  See https://github.com/kbknapp/clap-rs/issues/683 though.  It looks like clap doesn't work with Rust 1.10 in Debian stretch anymore; try installing rustc (and its dependencies) from Debian sid.

**Comment by brianmay** [comment] 2016-10-21 07:08
Ok, I tried installing rustc from unstable. Unfortunately another package fails to build. Unfortunately I don't have the details on this computer, however thought I should give you a status update anyway.

**Comment by joshtriplett** [comment] 2016-10-26 17:51
OK.  I'm going to close this issue, since upgrading to a newer version of rustc fixes it.  If you can reproduce the new package build issue, please report it as a build issue on that package, or post the log here and I'll do so.

**Closed by joshtriplett** 2016-10-26 17:51 UTC
